"""change float to decimal for monetary fields

Revision ID: 0913d3e12f97
Revises: 45e50dfeb64c
Create Date: 2026-05-13 16:34:14.471018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0913d3e12f97'
down_revision: Union[str, Sequence[str], None] = '45e50dfeb64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
