"""change payment relationship to one-to-one per order

Revision ID: 58fd83112a62
Revises: c9e585a5ae7e
Create Date: 2026-05-13 15:40:28.572300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fd83112a62'
down_revision: Union[str, Sequence[str], None] = 'c9e585a5ae7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
