"""Modelos updating

Revision ID: 68193302ba07
Revises: f030edbc243e
Create Date: 2026-05-13 15:36:05.027513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68193302ba07'
down_revision: Union[str, Sequence[str], None] = 'f030edbc243e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'user_id')
    op.drop_table('reviews')
    # ### end Alembic commands ###
