"""Modelos updated

Revision ID: aa2b4d8d50e9
Revises: ee8ede6d72f5
Create Date: 2026-05-11 16:45:34.802338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa2b4d8d50e9'
down_revision: Union[str, Sequence[str], None] = 'ee8ede6d72f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tags',
               existing_type=mysql.JSON(),
               nullable=True)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.alter_column('products', 'tags',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###
