"""remove total_amount column from orders table

Revision ID: afbfdef752b6
Revises: 58fd83112a62
Create Date: 2026-05-13 15:46:33.974587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afbfdef752b6'
down_revision: Union[str, Sequence[str], None] = '58fd83112a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
