"""add foreign keys and relationships to order, order_detail, and payment

Revision ID: c9e585a5ae7e
Revises: 68193302ba07
Create Date: 2026-05-13 15:39:00.871745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e585a5ae7e'
down_revision: Union[str, Sequence[str], None] = '68193302ba07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('order_details', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_details', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order_details', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.add_column('payments', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'order_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_column('order_details', 'product_id')
    op.drop_column('order_details', 'order_id')
    # ### end Alembic commands ###
