"""Update product Image entity

Revision ID: ee8ede6d72f5
Revises: 17c06f386cd1
Create Date: 2026-02-02 20:22:56.550035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8ede6d72f5'
down_revision: Union[str, Sequence[str], None] = '17c06f386cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('cloud_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'cloud_id')
    # ### end Alembic commands ###
